"""empty message

Revision ID: 342412faa29d
Revises: b5cb7f806bf6
Create Date: 2019-01-02 19:52:13.100510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342412faa29d'
down_revision = 'b5cb7f806bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'description')
    # ### end Alembic commands ###
