"""empty message

Revision ID: 77337317c6db
Revises: 342412faa29d
Create Date: 2019-01-08 12:41:42.662640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77337317c6db'
down_revision = '342412faa29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
