"""empty message

Revision ID: 7945566d9345
Revises: 77337317c6db
Create Date: 2019-01-08 13:06:47.536665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7945566d9345'
down_revision = '77337317c6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'created_by')
    # ### end Alembic commands ###
